# Generated by Django 5.1.3 on 2024-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_userdetails_address_userdetails_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='staff_images/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
