# Generated by Django 5.1.3 on 2024-12-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_staff_bio_remove_staff_image_staff_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory_images/')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myApp.servicetype')),
            ],
        ),
    ]
