# Generated by Django 5.1.3 on 2025-01-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
